### ISSUE TITLE
Problem loading system.lisp

### ISSUE THREAD

**Issue by ghost** [robert-strandh/Gsharp#2]
Hello i get this error by (load "system.lisp"):

* (load "system.lisp")

File-error in function LISP::INTERNAL-LOAD:  "system.lisp" does not exist.
   [Condition of type KERNEL:SIMPLE-FILE-ERROR]

Restarts:
  0: [CHECK-AGAIN] See if it exists now.
  1: [USE-VALUE  ] Prompt for a new name.
  2: [CONTINUE   ] Return NIL from load of "system.lisp".
  3: [ABORT      ] Return to Top-Level.

Debug  (type H for help)

(LISP::INTERNAL-LOAD #P"system.lisp" NIL :ERROR NIL ...)
Source: Error finding source: 
Error in function DEBUG::GET-FILE-TOP-LEVEL-FORM:  Source file no longer exists:
  target:code/load.lisp.

**Comment by robert-strandh** [comment]
Hello,

Maybe the documentation is not up to date, but that is not the way to 
install Gsharp.  You should do (asdf:load-system '#:gsharp).

However, Gsharp is currently broken, due to recent updates of McCLIM.
I do not have time to work on it at the moment.  Plus, I am planning
a second version of Gsharp, so I am not very motivated to work
on the existing code.
